# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273c46c812d5a5c888b95cf7181218db29d9c2bc13075c9d130d88c5c4dfae1c58659f6970174a11bd3dd3fcbcc3e012f49956e3cd933256adce57ed6e424f44

test:
  secret_key_base: 8a6218f3aa778226884e1b818d36dd0b817f7eed5f341eaeeff1a4b0927475214caebe94f6b09540a16769787c8bdc76d2a4db82d01ea131db750cab2bd5d337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
